[package]
name = "descramble"
version = "0.1.0"
edition = "2024"
author = "a22Dv"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

