[package]
name = "descramble"
version = "1.0.0"
edition = "2024"
author = "a22Dv"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
indicatif = "0.17.11"
itertools = "0.14.0"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

